import { Modal } from "react-bootstrap";

export const TwoFactorModal = ({ show, setShow }) => {
  const handleClose = () => {
    setShow(false);
  };
  return (
    <>
      <Modal
        show={show}
        onHide={handleClose}
      >
        <Modal.Header closeButton></Modal.Header>
        <Modal.Body className='text-white'>
          <h5 className='text-center'>Set Up 2FA</h5>

          <div className='text-start'>
            <p>
              <strong>Step 1: Get the App</strong> <br />
              Download and install Google Authenticator (iOS or Android) or
              Authy (iOS or Android).
            </p>
            <p>
              <strong>Step 2: Scan this Barcode</strong> <br />
              Tap the “+” icon in your authenticator app and scan the barcode
              using your device’s camera.
            </p>{" "}
            <br />
            <p className='text-center'>
              <a href='#'>
                <img
                  src='/assets/qr.png'
                  width='200'
                  alt=''
                  className='rounded-3'
                />
              </a>
            </p>
            <p className='text-center'>
              If you can’t scan the QR code, enter this code: <br />
              <strong>djhsetq35dsdgdi23</strong>
            </p>
            <br />
            <p>
              <strong>Step 3: Enter Code</strong> <br />
              Enter the 6 digit code generated by your authenticator app.
            </p>{" "}
            <br />
            <form
              action=''
              className='form-profile'
            >
              <div className='mb-3'>
                <input
                  type='text'
                  className='form-control'
                  placeholder='Enter 6 Digit Code'
                />
              </div>

              <div className='d-grid mt-2'>
                <button className='btn btn-primary py-3'>NEXT</button>
              </div>
            </form>
          </div>
        </Modal.Body>
      </Modal>
    </>
  );
};
